name: Finance Collector
on:
  schedule:
    - cron: '*/30 * * * *'   # каждые 30 минут
  workflow_dispatch: {}
permissions:
  contents: write   # нужно право на коммиты
jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node --version
      - run: node send-finance-collector.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "finance: update expenses CSV and state"
            git push
          else
            echo "No changes to commit"
          fi
